name: Build and Launch Robot in Gazebo

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang-format-10 file git python3-catkin-lint \
            python3-catkin-tools python3-pip python3-rosdep

      - name: Install pip dependencies
        run: pip install pre-commit
