name: Test with Pre-Built Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      
      - name: Set up Docker container
        run: |
          docker pull my-username/my-python-app:latest
          docker run --rm -v "${{ github.workspace }}:/app" mirgus/python-ubuntu24-test:latest /bin/bash -c "
            cd /app &&
            source venv/bin/activate &&
            python3 -m unittest discover -s tests"
